// Redline specs per component slug — the exact measurements an engineer
// implements and a designer cross-checks: color, padding, radius, height, font.
//
// Each row is { prop, token } or { prop, value }:
//   - token rows resolve to the token's current value at build time (and show a
//     swatch for colors), so specs never drift from the tokens.
//   - value rows are literals for things with no token (fixed sizes, opacity).
//
// These mirror the token choices in demos.css. Keep them in sync when a demo's
// styling changes. A slug with no entry simply shows the "Tokens used" list.

export const specs = {
  button: [
    { prop: 'Height (medium)', value: '40px' },
    { prop: 'Background', token: 'color/primary/base' },
    { prop: 'Label', token: 'color/static/white' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Padding Y', token: 'space/10' },
    { prop: 'Padding X', token: 'space/16' },
    { prop: 'Gap (icon)', token: 'space/6' },
    { prop: 'Font', token: 'type/label/sm' },
  ],
  'compact-button': [
    { prop: 'Size', value: '28 × 28px' },
    { prop: 'Icon', value: '16 × 16px' },
    { prop: 'Background', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Icon color', token: 'color/icon/sub-600' },
    { prop: 'Radius', token: 'radius/8' },
  ],
  'link-button': [
    { prop: 'Color', token: 'color/primary/base' },
    { prop: 'Font', token: 'type/label/sm' },
    { prop: 'Gap (icon)', token: 'space/4' },
    { prop: 'Hover', value: 'underline' },
  ],
  'social-button': [
    { prop: 'Height', value: '40px' },
    { prop: 'Background', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Label', token: 'color/text/sub-600' },
    { prop: 'Radius', token: 'radius/10' },
  ],
  'fancy-button': [
    { prop: 'Height', value: '40px' },
    { prop: 'Background', token: 'color/bg/strong-950' },
    { prop: 'Label', token: 'color/text/white-0' },
    { prop: 'Shadow', token: 'shadow/md' },
    { prop: 'Radius', token: 'radius/10' },
  ],
  'button-group': [
    { prop: 'Segment height', value: '36px' },
    { prop: 'Background', token: 'color/bg/white-0' },
    { prop: 'Selected background', token: 'color/bg/weak-50' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius (ends)', token: 'radius/8' },
    { prop: 'Padding', token: 'space/8' },
  ],
  badge: [
    { prop: 'Min height', value: '20px' },
    { prop: 'Filled background', token: 'color/primary/base' },
    { prop: 'Filled text', token: 'color/static/white' },
    { prop: 'Lighter background', token: 'color/state/information/lighter' },
    { prop: 'Radius', token: 'radius/full' },
    { prop: 'Padding X', token: 'space/8' },
    { prop: 'Font', token: 'type/label/xs' },
  ],
  'status-badge': [
    { prop: 'Completed bg', token: 'color/state/success/lighter' },
    { prop: 'Completed text', token: 'color/state/success/dark' },
    { prop: 'Radius', token: 'radius/full' },
    { prop: 'Padding', value: '2px 8px' },
    { prop: 'Font', token: 'type/label/xs' },
  ],
  tag: [
    { prop: 'Background', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Text', token: 'color/text/sub-600' },
    { prop: 'Radius', token: 'radius/6' },
    { prop: 'Padding Y', token: 'space/4' },
    { prop: 'Padding X', token: 'space/8' },
    { prop: 'Gap', token: 'space/6' },
    { prop: 'Font', token: 'type/paragraph/sm' },
  ],
  checkbox: [
    { prop: 'Box size', value: '20 × 20px' },
    { prop: 'Radius', token: 'radius/6' },
    { prop: 'Border (off)', token: 'color/stroke/sub-300' },
    { prop: 'Checked background', token: 'color/primary/base' },
    { prop: 'Check mark', token: 'color/static/white' },
    { prop: 'Focus ring', token: 'color/primary/alpha-16' },
    { prop: 'Label gap', token: 'space/8' },
  ],
  radio: [
    { prop: 'Circle size', value: '20 × 20px' },
    { prop: 'Radius', token: 'radius/full' },
    { prop: 'Border (off)', token: 'color/stroke/sub-300' },
    { prop: 'Selected background', token: 'color/primary/base' },
    { prop: 'Dot', token: 'color/static/white' },
    { prop: 'Label gap', token: 'space/8' },
  ],
  switch: [
    { prop: 'Track', value: '36 × 20px' },
    { prop: 'Thumb', value: '16 × 16px' },
    { prop: 'Off track', token: 'color/bg/soft-200' },
    { prop: 'On track', token: 'color/primary/base' },
    { prop: 'Thumb', token: 'color/static/white' },
    { prop: 'Thumb shadow', token: 'shadow/xs' },
  ],
  'text-input': [
    { prop: 'Height (medium)', value: '40px' },
    { prop: 'Background', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Text', token: 'color/text/strong-950' },
    { prop: 'Placeholder', token: 'color/text/soft-400' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Padding Y', token: 'space/10' },
    { prop: 'Padding X', token: 'space/12' },
    { prop: 'Focus border', token: 'color/primary/base' },
    { prop: 'Error border', token: 'color/state/error/base' },
    { prop: 'Font', token: 'type/paragraph/sm' },
  ],
  'text-area': [
    { prop: 'Min height', value: '84px' },
    { prop: 'Background', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Padding', token: 'space/12' },
    { prop: 'Font', token: 'type/paragraph/sm' },
  ],
  select: [
    { prop: 'Height (medium)', value: '40px' },
    { prop: 'Background', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Value text', token: 'color/text/strong-950' },
    { prop: 'Placeholder', token: 'color/text/soft-400' },
    { prop: 'Chevron', token: 'color/icon/soft-400' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Padding', token: 'space/12' },
  ],
  'tag-input': [
    { prop: 'Min height', value: '40px' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Chip radius', token: 'radius/6' },
    { prop: 'Padding', token: 'space/10' },
  ],
  'counter-input': [
    { prop: 'Height', value: '40px' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Stepper size', value: '28 × 28px' },
    { prop: 'Value font', token: 'type/paragraph/sm' },
  ],
  'digit-input': [
    { prop: 'Box size', value: '44 × 48px' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Focus border', token: 'color/primary/base' },
    { prop: 'Font', token: 'type/label/lg' },
    { prop: 'Gap', token: 'space/8' },
  ],
  slider: [
    { prop: 'Track height', value: '6px' },
    { prop: 'Track', token: 'color/bg/soft-200' },
    { prop: 'Fill', token: 'color/primary/base' },
    { prop: 'Thumb', value: '16 × 16px' },
    { prop: 'Thumb border', token: 'color/primary/base' },
    { prop: 'Radius', token: 'radius/full' },
  ],
  rating: [
    { prop: 'Star size', value: '22 × 22px' },
    { prop: 'Filled', token: 'color/state/away/base' },
    { prop: 'Empty', token: 'color/bg/soft-200' },
    { prop: 'Gap', token: 'space/4' },
  ],
  'date-picker': [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Selected day', token: 'color/primary/base' },
    { prop: 'Range fill', token: 'color/primary/alpha-10' },
    { prop: 'Day font', token: 'type/paragraph/xs' },
  ],
  'time-picker': [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Selected item', token: 'color/primary/alpha-10' },
    { prop: 'Selected text', token: 'color/primary/base' },
    { prop: 'Item font', token: 'type/paragraph/sm' },
  ],
  'file-upload': [
    { prop: 'Border', token: 'color/stroke/sub-300' },
    { prop: 'Border style', value: 'dashed' },
    { prop: 'Background', token: 'color/bg/weak-50' },
    { prop: 'Radius', token: 'radius/12' },
    { prop: 'Padding', token: 'space/24' },
    { prop: 'Icon', token: 'color/icon/soft-400' },
  ],
  'color-picker': [
    { prop: 'Swatch size', value: '24 × 24px' },
    { prop: 'Swatch radius', token: 'radius/full' },
    { prop: 'Selected ring', token: 'color/primary/base' },
    { prop: 'Gap', token: 'space/8' },
  ],
  'label-hint-text': [
    { prop: 'Label', token: 'color/text/strong-950' },
    { prop: 'Label font', token: 'type/label/sm' },
    { prop: 'Required mark', token: 'color/state/error/base' },
    { prop: 'Hint', token: 'color/text/soft-400' },
    { prop: 'Error hint', token: 'color/state/error/base' },
    { prop: 'Hint font', token: 'type/paragraph/xs' },
  ],
  'rich-editor': [
    { prop: 'Toolbar background', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Button size', value: '30 × 30px' },
    { prop: 'Active button', token: 'color/bg/weak-50' },
    { prop: 'Shadow', token: 'shadow/xs' },
  ],
  breadcrumbs: [
    { prop: 'Link', token: 'color/text/sub-600' },
    { prop: 'Current', token: 'color/text/strong-950' },
    { prop: 'Separator', token: 'color/text/disabled-300' },
    { prop: 'Font', token: 'type/paragraph/sm' },
    { prop: 'Gap', token: 'space/8' },
  ],
  pagination: [
    { prop: 'Cell size', value: '32 × 32px' },
    { prop: 'Radius', token: 'radius/8' },
    { prop: 'Selected background', token: 'color/primary/base' },
    { prop: 'Selected text', token: 'color/static/white' },
    { prop: 'Text', token: 'color/text/sub-600' },
    { prop: 'Font', token: 'type/paragraph/sm' },
  ],
  'tab-menu': [
    { prop: 'Track border', token: 'color/stroke/soft-200' },
    { prop: 'Active text', token: 'color/primary/base' },
    { prop: 'Active indicator', token: 'color/primary/base' },
    { prop: 'Inactive text', token: 'color/text/sub-600' },
    { prop: 'Gap', token: 'space/20' },
    { prop: 'Font', token: 'type/label/sm' },
  ],
  'step-indicator': [
    { prop: 'Step size', value: '24 × 24px' },
    { prop: 'Radius', token: 'radius/full' },
    { prop: 'Active', token: 'color/primary/base' },
    { prop: 'Completed', token: 'color/state/success/base' },
    { prop: 'Upcoming', token: 'color/bg/soft-200' },
    { prop: 'Font', token: 'type/label/xs' },
  ],
  alert: [
    { prop: 'Radius', token: 'radius/12' },
    { prop: 'Padding Y', token: 'space/12' },
    { prop: 'Padding X', token: 'space/16' },
    { prop: 'Success bg', token: 'color/state/success/lighter' },
    { prop: 'Success text', token: 'color/state/success/dark' },
    { prop: 'Icon size', value: '20 × 20px' },
    { prop: 'Font', token: 'type/paragraph/sm' },
  ],
  banner: [
    { prop: 'Background', token: 'color/state/information/lighter' },
    { prop: 'Text', token: 'color/state/information/dark' },
    { prop: 'Radius', token: 'radius/10' },
    { prop: 'Padding Y', token: 'space/12' },
    { prop: 'Padding X', token: 'space/16' },
    { prop: 'Font', token: 'type/paragraph/sm' },
  ],
  tooltip: [
    { prop: 'Background', token: 'color/bg/strong-950' },
    { prop: 'Text', token: 'color/text/white-0' },
    { prop: 'Radius', token: 'radius/8' },
    { prop: 'Padding Y', token: 'space/6' },
    { prop: 'Padding X', token: 'space/10' },
    { prop: 'Font', token: 'type/paragraph/xs' },
  ],
  'progress-bar': [
    { prop: 'Track height', value: '6px' },
    { prop: 'Track', token: 'color/bg/soft-200' },
    { prop: 'Fill', token: 'color/primary/base' },
    { prop: 'Radius', token: 'radius/full' },
  ],
  avatar: [
    { prop: 'Size (default)', value: '40 × 40px' },
    { prop: 'Radius', token: 'radius/full' },
    { prop: 'Fallback background', token: 'color/bg/soft-200' },
    { prop: 'Initials', token: 'color/text/sub-600' },
    { prop: 'Status dot', value: '11 × 11px' },
    { prop: 'Online status', token: 'color/state/success/base' },
  ],
  'segmented-control': [
    { prop: 'Track background', token: 'color/bg/weak-50' },
    { prop: 'Track radius', token: 'radius/10' },
    { prop: 'Track padding', token: 'space/2' },
    { prop: 'Active background', token: 'color/bg/white-0' },
    { prop: 'Active shadow', token: 'shadow/xs' },
    { prop: 'Item radius', token: 'radius/8' },
    { prop: 'Font', token: 'type/label/sm' },
  ],
  table: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/12' },
    { prop: 'Header background', token: 'color/bg/weak-50' },
    { prop: 'Header font', token: 'type/label/xs' },
    { prop: 'Cell padding', token: 'space/12' },
    { prop: 'Body font', token: 'type/paragraph/sm' },
  ],
  accordion: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/12' },
    { prop: 'Header padding Y', token: 'space/12' },
    { prop: 'Header padding X', token: 'space/16' },
    { prop: 'Header font', token: 'type/label/sm' },
    { prop: 'Chevron', token: 'color/icon/soft-400' },
  ],
  'activity-feed': [
    { prop: 'Avatar size', value: '28 × 28px' },
    { prop: 'Row gap', token: 'space/16' },
    { prop: 'Body text', token: 'color/text/sub-600' },
    { prop: 'Emphasis text', token: 'color/text/strong-950' },
    { prop: 'Timestamp', token: 'color/text/soft-400' },
    { prop: 'Font', token: 'type/paragraph/sm' },
  ],
  'notification-feed': [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Unread dot', token: 'color/primary/base' },
    { prop: 'Item font', token: 'type/paragraph/sm' },
  ],
  'content-divider': [
    { prop: 'Line', token: 'color/stroke/soft-200' },
    { prop: 'Label', token: 'color/text/soft-400' },
    { prop: 'Label font', token: 'type/subheading/xs' },
    { prop: 'Gap', token: 'space/12' },
  ],
  scroll: [
    { prop: 'Track width', value: '8px' },
    { prop: 'Track', token: 'color/bg/weak-50' },
    { prop: 'Thumb', token: 'color/bg/sub-300' },
    { prop: 'Radius', token: 'radius/full' },
  ],
  'widget-box': [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Shadow', token: 'shadow/xs' },
    { prop: 'Padding', token: 'space/16' },
    { prop: 'Content gap', token: 'space/12' },
  ],
  modal: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Shadow', token: 'shadow/md' },
    { prop: 'Padding', token: 'space/20' },
    { prop: 'Title font', token: 'type/label/md' },
    { prop: 'Body text', token: 'color/text/sub-600' },
  ],
  drawer: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Shadow', token: 'shadow/md' },
    { prop: 'Padding', token: 'space/20' },
  ],
  popover: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Shadow', token: 'shadow/md' },
    { prop: 'Padding Y', token: 'space/12' },
    { prop: 'Padding X', token: 'space/16' },
    { prop: 'Title font', token: 'type/label/sm' },
  ],
  dropdown: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Shadow', token: 'shadow/md' },
    { prop: 'Item radius', token: 'radius/8' },
    { prop: 'Item padding Y', token: 'space/8' },
    { prop: 'Selected item', token: 'color/primary/alpha-10' },
    { prop: 'Item font', token: 'type/paragraph/sm' },
  ],
  'command-menu': [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Border', token: 'color/stroke/soft-200' },
    { prop: 'Radius', token: 'radius/16' },
    { prop: 'Shadow', token: 'shadow/md' },
    { prop: 'Selected item', token: 'color/primary/alpha-10' },
    { prop: 'Item font', token: 'type/paragraph/sm' },
  ],
  sidebar: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Item radius', token: 'radius/8' },
    { prop: 'Item padding Y', token: 'space/8' },
    { prop: 'Active background', token: 'color/primary/alpha-10' },
    { prop: 'Active text', token: 'color/primary/base' },
    { prop: 'Item text', token: 'color/text/sub-600' },
    { prop: 'Item font', token: 'type/label/sm' },
  ],
  topbar: [
    { prop: 'Surface', token: 'color/bg/white-0' },
    { prop: 'Padding Y', token: 'space/12' },
    { prop: 'Padding X', token: 'space/16' },
    { prop: 'Title', token: 'color/text/strong-950' },
    { prop: 'Title font', token: 'type/label/md' },
  ],
  'page-header': [
    { prop: 'Padding', token: 'space/16' },
    { prop: 'Title', token: 'color/text/strong-950' },
    { prop: 'Title font', token: 'type/label/lg' },
    { prop: 'Description', token: 'color/text/sub-600' },
    { prop: 'Description font', token: 'type/paragraph/sm' },
  ],
  'empty-state': [
    { prop: 'Padding', token: 'space/24' },
    { prop: 'Illustration', value: '56 × 56px' },
    { prop: 'Illustration bg', token: 'color/bg/weak-50' },
    { prop: 'Title', token: 'color/text/strong-950' },
    { prop: 'Body', token: 'color/text/sub-600' },
    { prop: 'Content gap', token: 'space/8' },
  ],
};
