// build.mjs
// Reads tokens/figma.raw.json + inventory/components.json and generates:
//   tokens/tokens.json       DTCG-style tokens with light/dark values
//   tokens/variables.css     CSS custom properties (:root + dark overrides)
//   tokens/tailwind.theme.js Tailwind theme referencing the CSS vars
//   DESIGN-SYSTEM.md         the whole system as one agent-readable spec
//   site/                    a static, self-updating guideline site
//
// DESIGN-SYSTEM.md is the handoff artifact: a developer (or a coding agent)
// reads that one file and can build UI that matches the system without
// opening Figma. It is committed on purpose, unlike the other outputs.
// The docs site is themed BY the tokens it documents, so the page you read
// is a live sample of the system. No dependencies, pure Node stdlib.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  read, write, exists, slug, cssVar, unitFor,
  resolveTokens, groupByCategory,
} from './lib.mjs';

const ROOT = path.resolve(fileURLToPath(import.meta.url), '../..');
const p = (...a) => path.join(ROOT, ...a);

// Live demo HTML per component slug (token-based, restyles from the tokens —
// no Figma export). Kept in design-system/demos/, separate from the semantic
// spec in inventory/components.json. A missing entry just yields a spec-only page.
let DEMOS = {};
try {
  ({ demos: DEMOS } = await import('../demos/registry.mjs'));
} catch { DEMOS = {}; }
const demoFor = (c) => DEMOS[slug(c.name)] || null;

// Redline specs per slug (color/padding/height/…). A missing file is fine.
let SPECS = {};
try {
  ({ specs: SPECS } = await import('../demos/specs.mjs'));
} catch { SPECS = {}; }

const raw = read(p('tokens/figma.raw.json'));
const inventory = exists(p('inventory/components.json'))
  ? read(p('inventory/components.json'))
  : { components: [] };

// Optional catalog of not-yet-built components. Any template whose name is not
// already a real component is rendered as a "planned" placeholder page, so the
// docs show the roadmap. To promote one, move its entry into components.json.
const templates = exists(p('inventory/component-templates.json'))
  ? (read(p('inventory/component-templates.json')).components || [])
  : [];
const realNames = new Set(inventory.components.map((c) => c.name.toLowerCase()));
const plannedTemplates = templates
  .filter((t) => !realNames.has((t.name || '').toLowerCase()))
  .map((t) => ({ ...t, status: 'planned', codeConnected: false, _template: true }));
const allComponents = [...inventory.components, ...plannedTemplates];

const { flat, warnings } = resolveTokens(raw);
if (warnings.length) warnings.forEach((w) => console.warn('  warn:', w));

function cssValue(name, rec, mode) {
  const v = rec[mode];
  if (v === undefined || v === null) return null;
  if (rec.type === 'FLOAT') return `${v}${unitFor(name)}`;
  return String(v);
}

// ---- tokens.json (DTCG-ish, modes under $value) ----
const dtcg = {};
for (const [name, rec] of Object.entries(flat)) {
  const parts = name.split('/');
  let node = dtcg;
  for (let i = 0; i < parts.length - 1; i++) node = node[parts[i]] ||= {};
  node[parts[parts.length - 1]] = {
    $type: rec.type.toLowerCase(),
    $value: { light: rec.light, dark: rec.dark },
  };
}
write(p('tokens/tokens.json'), dtcg);

// ---- variables.css ----
{
  const light = [], dark = [];
  for (const [name, rec] of Object.entries(flat)) {
    const l = cssValue(name, rec, 'light');
    const d = cssValue(name, rec, 'dark');
    if (l != null) light.push(`  ${cssVar(name)}: ${l};`);
    if (d != null && d !== l) dark.push(`  ${cssVar(name)}: ${d};`);
  }
  const css =
`/* Generated by build.mjs. Do not edit by hand. Source of truth: Figma variables. */
:root {
${light.join('\n')}
}

:root[data-theme="dark"] {
${dark.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark.join('\n')}
  }
}
`;
  write(p('tokens/variables.css'), css);
}

// ---- tailwind.theme.js ----
{
  const buckets = { colors: {}, spacing: {}, borderRadius: {}, fontSize: {}, fontWeight: {}, boxShadow: {} };
  const put = (bucket, key, name) => { buckets[bucket][key] = `var(${cssVar(name)})`; };
  for (const [name] of Object.entries(flat)) {
    const [head, ...rest] = name.split('/');
    const tail = rest.join('-');
    if (head === 'color') put('colors', tail, name);
    else if (head === 'space') put('spacing', tail, name);
    else if (head === 'radius') put('borderRadius', tail, name);
    else if (head === 'font' && rest[0] === 'size') put('fontSize', rest.slice(1).join('-'), name);
    else if (head === 'font' && rest[0] === 'weight') put('fontWeight', rest.slice(1).join('-'), name);
    else if (head === 'shadow') put('boxShadow', tail, name);
  }
  const js =
`// Generated by build.mjs. In tailwind.config.js:  theme: { extend: require('./tokens/tailwind.theme.js') }
module.exports = ${JSON.stringify(buckets, null, 2)};
`;
  write(p('tokens/tailwind.theme.js'), js);
}

// ---------- docs site ----------
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const groups = groupByCategory(flat);

const CATEGORY_ORDER = ['Actions', 'Forms', 'Layout', 'Navigation', 'Feedback', 'Data display', 'Overlays'];
const STATUSES = ['stable', 'beta', 'deprecated', 'planned'];

// Components grouped by category, in a stable order (known categories first).
function componentGroups() {
  const map = new Map();
  for (const c of allComponents) {
    const cat = c.category || 'Components';
    if (!map.has(cat)) map.set(cat, []);
    map.get(cat).push(c);
  }
  const cats = [
    ...CATEGORY_ORDER.filter((c) => map.has(c)),
    ...[...map.keys()].filter((c) => !CATEGORY_ORDER.includes(c)),
  ];
  return cats.map((cat) => [cat, map.get(cat)]);
}

function statusOf(c) {
  const s = (c.status || 'stable').toLowerCase();
  return STATUSES.includes(s) ? s : 'stable';
}
function statusBadge(c) {
  const s = statusOf(c);
  return `<span class="st-badge st-${s}">${esc(s)}</span>`;
}

// Shared client script: theme toggle + mobile drawer + component filter.
const SHELL_JS = `
  const root = document.documentElement;
  const saved = localStorage.getItem('theme');
  if (saved) root.setAttribute('data-theme', saved);
  document.getElementById('theme').addEventListener('click', () => {
    const next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    root.setAttribute('data-theme', next);
    localStorage.setItem('theme', next);
  });
  const menu = document.getElementById('menu');
  const backdrop = document.getElementById('backdrop');
  const closeNav = () => { document.body.classList.remove('nav-open'); menu.setAttribute('aria-expanded', 'false'); backdrop.hidden = true; };
  const openNav = () => { document.body.classList.add('nav-open'); menu.setAttribute('aria-expanded', 'true'); backdrop.hidden = false; };
  menu.addEventListener('click', () => document.body.classList.contains('nav-open') ? closeNav() : openNav());
  backdrop.addEventListener('click', closeNav);
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape') closeNav(); });
  document.querySelectorAll('.side a').forEach((a) => a.addEventListener('click', closeNav));
  const filter = document.getElementById('navfilter');
  if (filter) filter.addEventListener('input', () => {
    const q = filter.value.trim().toLowerCase();
    document.querySelectorAll('.nav-group').forEach((g) => {
      let any = false;
      g.querySelectorAll('a[data-name]').forEach((a) => {
        const hit = a.dataset.name.includes(q);
        a.hidden = !hit; if (hit) any = true;
      });
      g.hidden = !any;
    });
  });
  document.querySelectorAll('.tabs').forEach((tabs) => {
    const btns = tabs.querySelectorAll('.tab');
    btns.forEach((btn) => btn.addEventListener('click', () => {
      btns.forEach((b) => { b.classList.remove('is-active'); b.setAttribute('aria-selected', 'false'); });
      btn.classList.add('is-active'); btn.setAttribute('aria-selected', 'true');
      tabs.querySelectorAll('.tabpanel').forEach((pan) => pan.classList.toggle('is-hidden', pan.dataset.panel !== btn.dataset.tab));
    }));
  });
  document.querySelectorAll('.copy').forEach((b) => b.addEventListener('click', () => {
    const box = b.closest('.tabpanel') || b.closest('.snippet');
    const code = box.querySelector('code').textContent;
    navigator.clipboard.writeText(code).then(() => {
      const prev = b.textContent; b.textContent = 'Copied'; b.classList.add('is-copied');
      setTimeout(() => { b.textContent = prev; b.classList.remove('is-copied'); }, 1200);
    });
  }));
`;

function navMarkup(up) {
  const groupsHtml = componentGroups().map(([cat, items]) => {
    const links = items.map((c) =>
      `<a href="${up}components/${slug(c.name)}.html" data-name="${esc(c.name.toLowerCase())}"><span class="dot st-${statusOf(c)}" title="${statusOf(c)}"></span>${esc(c.name)}</a>`
    ).join('');
    return `<div class="nav-group"><p class="nav-group-title">${esc(cat)}</p>${links}</div>`;
  }).join('');
  // Foundations sub-sections link to the anchors on the index page.
  const foundations = [['Color', 'color'], ['Spacing', 'space'], ['Radius', 'radius'], ['Typography', 'type'], ['Shadows', 'shadow']];
  const foundationLinks = foundations
    .filter(([, id]) => groups[id])
    .map(([label, id]) => `<a href="${up}index.html#${id}" data-name="${esc(label.toLowerCase())}">${esc(label)}</a>`)
    .join('');
  return `
    <a href="${up}index.html" class="side-lead">Foundations</a>
    <div class="side-filter">
      <svg class="side-filter-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5"/></svg>
      <input id="navfilter" type="search" placeholder="Search..." autocomplete="off" aria-label="Search foundations and components">
    </div>
    <div class="nav-groups">
      <div class="nav-group"><p class="nav-group-title">Foundations</p>${foundationLinks}</div>
      ${groupsHtml}
    </div>`;
}

function shell(title, body, depth = 0) {
  const up = '../'.repeat(depth);
  const name = raw.meta?.name || 'Design system';
  return `<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} &middot; ${esc(name)}</title>
<link rel="stylesheet" href="${up}assets/tokens.css">
<link rel="stylesheet" href="${up}assets/site.css">
<link rel="stylesheet" href="${up}assets/demos.css">
</head>
<body>
<header class="topbar">
  <button id="menu" class="menu" aria-label="Toggle navigation" aria-expanded="false" aria-controls="side"><span></span><span></span><span></span></button>
  <a class="brand" href="${up}index.html">${esc(name)}</a>
  <button id="theme" class="theme" aria-label="Toggle color theme">Theme</button>
</header>
<div class="backdrop" id="backdrop" hidden></div>
<div class="layout">
  <nav class="side" id="side" aria-label="Components">${navMarkup(up)}</nav>
  <main class="content">${body}</main>
</div>
<script>${SHELL_JS}</script>
</body>
</html>`;
}

// ---- Color foundations ----
// Follows the patterns established design systems use (GitHub Primer, Radix,
// IBM Carbon): lead with SEMANTIC tokens grouped by the role they play, and
// present the PRIMITIVE scales as compact one-row-per-hue ramps for reference,
// rather than a flat wall of equal-weight swatches.

const ROLE_LABELS = {
  bg: ['Background', 'Surfaces, from page canvas to inverted fills.'],
  text: ['Text', 'By emphasis: strong → sub → soft → disabled.'],
  icon: ['Icon', 'Same emphasis ladder as text.'],
  stroke: ['Stroke', 'Borders and dividers.'],
  primary: ['Primary', 'The brand / action color. Rebrand by repointing these.'],
  state: ['State', 'Intent colors. Per state: lighter · light · base · dark.'],
  static: ['Static', 'Never invert between light and dark.'],
};
const HUE_ORDER = ['gray', 'slate', 'blue', 'orange', 'red', 'green', 'yellow', 'purple', 'sky', 'pink', 'teal'];

// A compact semantic row: swatch + token + light/dark values.
function semRow(t) {
  const l = t.light ?? '', d = t.dark ?? '';
  const dark = d && d !== l ? `<span class="cval cval--dark" title="dark mode">${esc(d)}</span>` : '';
  return `<div class="crow">
    <span class="chip xs" style="background: var(${cssVar(t.name)})"></span>
    <code>${esc(t.name)}</code>
    <span class="cval" title="light mode">${esc(l)}</span>${dark}
  </div>`;
}

// A primitive hue ramp: one row of numbered steps (Radix/Tailwind style).
function ramp(name, steps) {
  const cells = steps.map((t) => {
    const step = t.name.split('/').pop();
    return `<span class="ramp-step" style="background: var(${cssVar(t.name)})" title="${esc(t.name)} · ${esc(t.light ?? '')}"><em>${esc(step)}</em></span>`;
  }).join('');
  return `<div class="ramp"><span class="ramp-name">${esc(name)}</span><div class="ramp-steps">${cells}</div></div>`;
}

function colorSection(items) {
  const semantic = items.filter((t) => t.collection !== 'primitives');
  const primitive = items.filter((t) => t.collection === 'primitives');

  // Semantic, grouped by role (color/<role>/...).
  const byRole = new Map();
  for (const t of semantic) {
    const role = t.name.split('/')[1];
    if (!byRole.has(role)) byRole.set(role, []);
    byRole.get(role).push(t);
  }
  const roleKeys = [...Object.keys(ROLE_LABELS).filter((r) => byRole.has(r)),
    ...[...byRole.keys()].filter((r) => !ROLE_LABELS[r])];
  const semHtml = roleKeys.map((role) => {
    const [label, note] = ROLE_LABELS[role] || [role[0].toUpperCase() + role.slice(1), ''];
    return `<div class="role-group">
      <div class="role-head"><h4>${esc(label)}</h4>${note ? `<p>${esc(note)}</p>` : ''}</div>
      <div class="crows">${byRole.get(role).map(semRow).join('')}</div>
    </div>`;
  }).join('');

  // Primitive, one ramp per hue; leftovers (alpha/overlays) as compact rows.
  const byHue = new Map();
  const leftovers = [];
  for (const t of primitive) {
    const hue = t.name.split('/')[1];
    if (HUE_ORDER.includes(hue)) {
      if (!byHue.has(hue)) byHue.set(hue, []);
      byHue.get(hue).push(t);
    } else leftovers.push(t);
  }
  const numStep = (t) => Number(t.name.split('/').pop().replace(/[^0-9.]/g, '')) || 0;
  const ramps = [...HUE_ORDER.filter((h) => byHue.has(h))]
    .map((h) => ramp(h[0].toUpperCase() + h.slice(1), byHue.get(h).sort((a, b) => numStep(a) - numStep(b))))
    .join('');
  const leftoverHtml = leftovers.length
    ? `<div class="role-group"><div class="role-head"><h4>Alpha &amp; overlays</h4><p>Transparent tints for hovers, focus rings, scrims.</p></div><div class="crows">${leftovers.map(semRow).join('')}</div></div>`
    : '';

  return `<section id="color">
    <h2>Color</h2>
    <h3 class="sub-head">Semantic tokens <span class="sub-note">— use these in UI</span></h3>
    <div class="role-groups">${semHtml}</div>
    <h3 class="sub-head">Primitive scales <span class="sub-note">— reference only; define semantics, don't use directly</span></h3>
    <div class="ramps">${ramps}${leftoverHtml}</div>
  </section>`;
}

function scaleRow(t) {
  return `<tr><td><code>${esc(t.name)}</code></td><td class="mono">${esc(t.light ?? '')}</td></tr>`;
}
function compCard(c) {
  const d = demoFor(c);
  const inner = (d && d.preview) || c.preview || '<span class="stage-empty">Preview pending</span>';
  const cls = c._template ? 'comp-card comp-card--template' : 'comp-card';
  return `<a class="${cls}" href="components/${slug(c.name)}.html">
    <div class="stage stage--thumb ds-demo">${inner}</div>
    <div class="comp-card-meta"><strong>${esc(c.name)} ${statusBadge(c)}</strong><span>${esc(c.tagline || c.description || '')}</span></div>
  </a>`;
}

function foundationsPage() {
  const order = ['color', 'space', 'radius', 'type', 'font', 'shadow'];
  const cats = [...order.filter((c) => groups[c]), ...Object.keys(groups).filter((c) => !order.includes(c))];
  const sections = cats.map((cat) => {
    const items = groups[cat];
    if (cat === 'color') return colorSection(items);
    return `<section id="${cat}"><h2>${esc(cat[0].toUpperCase() + cat.slice(1))}</h2>
      <table class="scale"><tbody>${items.map(scaleRow).join('')}</tbody></table></section>`;
  }).join('');
  const compSections = componentGroups().map(([cat, items]) =>
    `<h3 class="cat-head">${esc(cat)}</h3><div class="comp-grid">${items.map(compCard).join('')}</div>`
  ).join('');
  const body = `
    <div class="hero">
      <p class="eyebrow">Living guideline</p>
      <h1>${esc(raw.meta?.name || 'Design system')}</h1>
      <p class="lede">Generated from Figma variables. Everything on this page is rendered with the tokens it documents, so it stays true to the source. Last built ${new Date().toISOString().slice(0, 10)}.</p>
    </div>
    ${sections}
    <section id="components"><h2>Components</h2>${compSections}</section>`;
  return shell('Foundations', body, 0);
}

// A copyable code block (TSX only — the component call a developer writes).
function codeBlock(code) {
  return `<div class="code-wrap"><pre class="code"><code>${esc(code)}</code></pre><div class="code-actions"><button class="copy" type="button">Copy</button></div></div>`;
}

// Specs are per-variant (a size or type changes color/padding/height), so they
// live inside each variant, not in one component-wide table. specs.mjs entries
// may be a flat array (shared base) or { base, byVariant } — normalize both.
function getSpecs(c) {
  const s = SPECS[slug(c.name)];
  if (!s) return { base: [], byVariant: {} };
  if (Array.isArray(s)) return { base: s, byVariant: {} };
  return { base: s.base || [], byVariant: s.byVariant || {} };
}
// Resolve one spec row to a table row (token → current value, + swatch for colors).
function specRowHtml(r) {
  if (r.token) {
    const rec = flat[r.token];
    const val = rec ? (cssValue(r.token, rec, 'light') ?? String(rec.light ?? '')) : '';
    const sw = rec?.type === 'COLOR' ? `<span class="chip sm" style="background: var(${cssVar(r.token)})"></span>` : '';
    return `<tr><td>${esc(r.prop)}</td><td>${sw}<code>${esc(r.token)}</code></td><td class="mono">${esc(val)}</td></tr>`;
  }
  return `<tr><td>${esc(r.prop)}</td><td class="muted">literal</td><td class="mono">${esc(r.value ?? '')}</td></tr>`;
}
function specTable(rows) {
  if (!rows.length) return '';
  return `<table class="specs"><thead><tr><th>Property</th><th>Token</th><th>Value</th></tr></thead><tbody>${rows.map(specRowHtml).join('')}</tbody></table>`;
}

// Derive Tailwind utility classes for a spec row, using the generated theme
// keys (color/primary/base → bg-primary-base, radius/10 → rounded-10, …). Rows
// we can't map cleanly (font/type shorthand) are skipped — Specs still lists them.
function twClassFromRow(r) {
  const label = (r.prop || '').toLowerCase();
  const tok = r.token || '';
  const colorKey = tok.startsWith('color/') ? tok.slice(6).replace(/\//g, '-') : null;
  const seg = tok.split('/')[1];
  const radiusKey = tok.startsWith('radius/') ? seg : null;
  const spaceKey = tok.startsWith('space/') ? seg : null;
  const shadowKey = tok.startsWith('shadow/') ? seg : null;
  const lit = r.value;
  if (/background|surface|track|fill/.test(label)) return colorKey ? `bg-${colorKey}` : (lit === 'transparent' ? 'bg-transparent' : null);
  if (/border|stroke|outline/.test(label) && colorKey) return `border border-${colorKey}`;
  if (/(text|label|value|title)/.test(label) && colorKey) return `text-${colorKey}`;
  if (/(icon|chevron|dot)/.test(label) && colorKey) return `text-${colorKey}`;
  if (/radius/.test(label) && radiusKey) return `rounded-${radiusKey}`;
  if (/padding x/.test(label) && spaceKey) return `px-${spaceKey}`;
  if (/padding y/.test(label) && spaceKey) return `py-${spaceKey}`;
  if (/padding/.test(label) && spaceKey) return `p-${spaceKey}`;
  if (/gap/.test(label) && spaceKey) return `gap-${spaceKey}`;
  if (/shadow/.test(label) && shadowKey) return `shadow-${shadowKey}`;
  if (/height/.test(label)) return spaceKey ? `h-${spaceKey}` : (/^\d+px$/.test(lit || '') ? `h-[${lit}]` : null);
  return null;
}
function tailwindFromSpecs(rows) {
  const seen = new Set(), out = [];
  for (const r of rows || []) {
    const c = twClassFromRow(r);
    if (!c) continue;
    for (const cc of c.split(' ')) if (!seen.has(cc)) { seen.add(cc); out.push(cc); }
  }
  return out.join(' ');
}

// One variant card: a live stage, then a tabbed Specs / Code panel. Specs is
// the redline (base rows + any rows specific to this variant); Code shows both
// the component call and the equivalent Tailwind token classes (from the specs).
// Tabs keep it clean; a single panel renders without a tablist.
function renderVariant(v, specRows) {
  const desc = v.description ? `<p class="variant-desc">${esc(v.description)}</p>` : '';
  const stage = v.html
    ? `<div class="stage stage--variant ds-demo">${v.html}</div>`
    : '';
  const panels = [];
  if (specRows && specRows.length) panels.push(['specs', 'Specs', specTable(specRows)]);
  const twcls = tailwindFromSpecs(specRows);
  const codeParts = [];
  if (v.tsx) codeParts.push(codeBlock(v.tsx));
  if (twcls) codeParts.push(`<p class="code-caption">Or style any element with the Tailwind token classes:</p>${codeBlock(`<div className="${esc(twcls)}">…</div>`)}`);
  if (codeParts.length) panels.push(['code', 'Code', codeParts.join('')]);

  let detail = '';
  if (panels.length === 1) {
    detail = `<div class="tabs tabs--single"><div class="tabpanel" data-panel="${panels[0][0]}">${panels[0][2]}</div></div>`;
  } else if (panels.length > 1) {
    const tabs = panels.map((pan, i) =>
      `<button class="tab${i === 0 ? ' is-active' : ''}" type="button" role="tab" aria-selected="${i === 0}" data-tab="${pan[0]}">${pan[1]}</button>`
    ).join('');
    const bodies = panels.map((pan, i) =>
      `<div class="tabpanel${i === 0 ? '' : ' is-hidden'}" role="tabpanel" data-panel="${pan[0]}">${pan[2]}</div>`
    ).join('');
    detail = `<div class="tabs"><div class="tablist" role="tablist">${tabs}</div>${bodies}</div>`;
  }
  return `<div class="variant">
    <div class="variant-head"><h3>${esc(v.title || '')}</h3>${desc}</div>
    ${stage}
    ${detail}
  </div>`;
}

// Bridge inventory `examples` (title/usage/description) to the variant shape,
// so components without a demo-registry entry still list their variants (TSX
// only, no live stage).
function variantsFor(c) {
  const d = demoFor(c);
  if (d && d.variants && d.variants.length) return d.variants;
  return (c.examples || [])
    .filter((ex) => ex.usage || ex.title)
    .map((ex) => ({ title: ex.title, description: ex.description, tsx: ex.usage }));
}

function componentPage(c) {
  const d = demoFor(c);

  // Import
  const importLine = c.usage?.import
    ? `<section><h2>Import</h2><div class="snippet snippet--solo"><div class="snippet-bar"><span>Import</span><button class="copy" type="button">Copy</button></div><pre class="code"><code>${esc(c.usage.import)}</code></pre></div></section>`
    : '';

  // Variants (live stage + TSX + per-variant specs). Specs = shared base rows
  // merged with any rows specific to this variant (its title matches byVariant).
  const { base: specBase, byVariant } = getSpecs(c);
  const variants = variantsFor(c);
  const variantsSection = variants.length
    ? `<section><h2>Variants</h2>${variants.map((v) => {
        const rows = [...specBase, ...(byVariant[v.title] || [])];
        return renderVariant(v, rows);
      }).join('')}</section>`
    : '';

  // Anatomy: ONE live instance + the numbered part list (what it is made of).
  const parts = c.anatomy || d?.anatomy?.parts || [];
  const partList = parts.map((a) => `<li>${esc(a)}</li>`).join('');
  const anatomyStage = d?.anatomy?.html
    ? `<div class="stage stage--variant ds-demo ds-anatomy-stage">${d.anatomy.html}</div>`
    : '';
  const anatomy = (partList || anatomyStage)
    ? `<section><h2>Anatomy</h2>${anatomyStage}${partList ? `<ol class="anatomy">${partList}</ol>` : ''}</section>`
    : '';

  // Interaction states: a playable instance + a forced-state grid.
  const stateItems = (d?.states || []).map((s) =>
    `<figure class="state-cell"><div class="stage stage--state ds-demo">${s.html}</div><figcaption>${esc(s.label)}</figcaption></figure>`
  ).join('');
  const statesSection = stateItems
    ? `<section><h2>States</h2>
        <p class="section-note">Hover, focus, or click the live component above to try its states. Every state is shown below.</p>
        <div class="state-grid">${stateItems}</div>
      </section>`
    : '';

  // API — props only. Interaction states now have their own section.
  const propRows = (c.props || []).map((pr) =>
    `<tr><td><code>${esc(pr.name)}</code></td><td>${(pr.values || []).map((v) => `<span class="tag">${esc(v)}</span>`).join(' ')}</td></tr>`
  );
  const api = propRows.length
    ? `<section><h2>API</h2><table class="scale"><tbody>${propRows.join('')}</tbody></table></section>`
    : '';

  const tokensUsed = (c.tokensUsed || []).map((t) =>
    `<li><span class="chip sm" style="background: var(${cssVar(t)})"></span><code>${esc(t)}</code></li>`
  ).join('');
  const dos = (c.usage?.do || []).map((x) => `<li>${esc(x)}</li>`).join('');
  const donts = (c.usage?.dont || []).map((x) => `<li>${esc(x)}</li>`).join('');
  const code = c._template
    ? `<p class="template-note">Not in the Figma file yet — this page is the agreed spec. Once it ships, move it to <code>inventory/components.json</code> and add the final tokens and a demo.</p>`
    : c.codeConnected
      ? `<p class="connected">Code-connected &rarr; <code>${esc(c.codePath || '')}</code></p>`
      : `<p class="unconnected">In the design system, not yet in code. Scaffold it from this spec (see the build-ui flow) instead of hand-rolling a different API.</p>`;

  const body = `
    <div class="crumb"><a href="../index.html">Foundations</a> / ${esc(c.category || 'Components')} / ${esc(c.name)}</div>
    <div class="comp-head"><h1>${esc(c.name)}</h1>${statusBadge(c)}</div>
    <p class="lede">${esc(c.description || '')}</p>
    ${code}
    ${importLine}
    ${variantsSection}
    ${anatomy}
    ${statesSection}
    ${api}
    ${(!specBase.length && tokensUsed) ? `<section><h2>Tokens used</h2><ul class="tokenlist">${tokensUsed}</ul></section>` : ''}
    ${(dos || donts) ? `<section class="usage">
      <div><h2>Do</h2><ul class="do">${dos}</ul></div>
      <div><h2>Don't</h2><ul class="dont">${donts}</ul></div>
    </section>` : ''}`;
  return shell(c.name, body, 1);
}

// Copy generated variables.css + the live-demo styles into the site so the
// hosted docs are self-contained.
write(p('site/assets/tokens.css'), fs.readFileSync(p('tokens/variables.css'), 'utf8'));
if (exists(p('demos/demos.css'))) {
  write(p('site/assets/demos.css'), fs.readFileSync(p('demos/demos.css'), 'utf8'));
}

const SITE_CSS = `
:root { --maxw: 940px; --gap: clamp(16px, 3vw, 40px); --topbar-h: 61px; --side-w: 260px; }
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--color-bg-white-0, #fff);
  color: var(--color-text-strong-950, #171717);
  font-family: var(--font-family-sans, ui-sans-serif, system-ui, sans-serif);
  font-size: 16px; line-height: 1.65;
}
a { color: inherit; }
code, .mono { font-family: inherit; font-size: inherit; }
.topbar {
  display: flex; align-items: center; gap: 12px;
  padding: 14px var(--gap); border-bottom: 1px solid var(--color-stroke-soft-200, #ebebeb);
  position: sticky; top: 0; background: var(--color-bg-white-0, #fff); z-index: 25;
}
.brand { font-weight: 500; text-decoration: none; letter-spacing: -0.01em; margin-right: auto; }
.theme {
  font: inherit; font-size: 13px; cursor: pointer; padding: 6px 12px;
  border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-full, 999px);
  background: transparent; color: inherit;
}
.menu {
  display: none; flex-direction: column; justify-content: center; gap: 4px;
  width: 38px; height: 38px; padding: 0 9px; cursor: pointer;
  border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-8, 8px);
  background: transparent; flex: none;
}
.menu span { display: block; height: 2px; border-radius: 2px; background: var(--color-text-strong-950, #171717); transition: transform .2s ease, opacity .2s ease; }
body.nav-open .menu span:nth-child(1) { transform: translateY(6px) rotate(45deg); }
body.nav-open .menu span:nth-child(2) { opacity: 0; }
body.nav-open .menu span:nth-child(3) { transform: translateY(-6px) rotate(-45deg); }
.backdrop { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 15; }
.layout {
  display: block;
  padding-left: var(--side-w);
  min-height: calc(100vh - var(--topbar-h));
}
.side {
  position: fixed; top: var(--topbar-h); left: 0; bottom: 0;
  width: var(--side-w); z-index: 20;
  display: flex; flex-direction: column; gap: 2px;
  padding: 24px 16px; overflow-y: auto;
  background: var(--color-bg-white-0, #fff);
  border-right: 1px solid var(--color-stroke-soft-200, #ebebeb);
}
.side a { display: flex; align-items: center; text-decoration: none; padding: 6px 8px; border-radius: 6px; font-size: 14px; color: var(--color-text-sub-600, #5c5c5c); }
.side a:hover { background: var(--color-bg-weak-50, #f7f7f7); color: var(--color-text-strong-950, #171717); }
.side-lead { color: var(--color-text-strong-950, #171717) !important; font-weight: 500; }
.side-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--color-text-sub-600, #a3a3a3); margin: 18px 8px 4px; }
.side-filter { position: relative; margin: 12px 0 4px; }
.side-filter-icon {
  position: absolute; left: 10px; top: 50%; transform: translateY(-50%);
  color: var(--color-text-sub-600, #a3a3a3); pointer-events: none;
}
.side-filter input {
  width: 100%; font: inherit; font-size: 13px; padding: 7px 10px 7px 30px;
  border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-8, 8px);
  background: var(--color-bg-weak-50, #f7f7f7); color: inherit;
}
.side-filter input:focus { outline: 2px solid var(--color-primary-base, #335cff); outline-offset: 1px; }
.nav-group { margin-bottom: 6px; }
.nav-group-title { font-size: 11px; text-transform: uppercase; letter-spacing: 0.07em; color: var(--color-text-sub-600, #a3a3a3); margin: 12px 8px 2px; font-weight: 500; }
.dot { display: inline-block; width: 7px; height: 7px; border-radius: 999px; margin-right: 9px; flex: none; background: var(--color-text-sub-600, #a3a3a3); }
.dot.st-stable { background: #3f9142; } .dot.st-beta { background: #b5850b; } .dot.st-deprecated { background: #c0392b; } .dot.st-planned { background: #a8a69c; }
.st-badge { display: inline-block; font-size: 10px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.05em; padding: 2px 8px; border-radius: 999px; border: 1px solid currentColor; line-height: 1.5; }
.st-badge.st-stable { color: #3f9142; } .st-badge.st-beta { color: #b5850b; } .st-badge.st-deprecated { color: #c0392b; } .st-badge.st-planned { color: var(--color-text-sub-600, #a3a3a3); }
.content { padding: 40px var(--gap) 96px; min-width: 0; max-width: calc(var(--maxw) + 2 * var(--gap)); }
.eyebrow { text-transform: uppercase; letter-spacing: 0.1em; font-size: 12px; color: var(--color-primary-base, #335cff); margin: 0 0 8px; }
h1 { font-size: clamp(30px, 5vw, 44px); line-height: 1.05; letter-spacing: -0.02em; font-weight: 500; margin: 0 0 12px; }
h2 { font-size: 15px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--color-text-sub-600, #5c5c5c); font-weight: 500; margin: 48px 0 16px; padding-bottom: 8px; border-bottom: 1px solid var(--color-stroke-soft-200, #ebebeb); }
.comp-head { display: flex; align-items: center; gap: 14px; flex-wrap: wrap; }
.comp-head h1 { margin: 0; }
.lede { font-size: 18px; color: var(--color-text-sub-600, #5c5c5c); max-width: 60ch; margin: 12px 0 24px; }
.hero { padding: 24px 0 8px; }
.chip.sm { display: inline-block; width: 16px; height: 16px; border-radius: 4px; vertical-align: -3px; margin-right: 8px; }
.chip.xs { display: inline-block; width: 18px; height: 18px; border-radius: 5px; border: 1px solid var(--color-stroke-soft-200, #ebebeb); flex: none; }

/* Color: sub-headers */
.sub-head { font-size: 15px; font-weight: 500; text-transform: none; letter-spacing: 0; color: var(--color-text-strong-950, #171717); border: 0; padding: 0; margin: 56px 0 24px; }
.sub-head:first-of-type { margin-top: 32px; }
.sub-note { color: var(--color-text-soft-400, #a3a3a3); font-weight: 400; }

/* Color: semantic role groups */
.role-groups { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 48px 40px; }
.role-head h4 { margin: 0; font-size: 14px; font-weight: 500; }
.role-head p { margin: 4px 0 14px; font-size: 12px; color: var(--color-text-soft-400, #a3a3a3); }
.crows { display: flex; flex-direction: column; }
.crow { display: flex; align-items: center; gap: 10px; padding: 5px 0; border-bottom: 1px solid var(--color-stroke-soft-200, #f2f2f2); font-size: 13px; }
.crow code { flex: 1; min-width: 0; }
.crow .cval { font-size: 12px; color: var(--color-text-sub-600, #64625c); font-variant-numeric: tabular-nums; }
.crow .cval--dark { color: var(--color-text-soft-400, #a3a3a3); }
.crow .cval--dark::before { content: "/ "; }

/* Color: primitive ramps */
.ramps { display: flex; flex-direction: column; gap: 12px; }
.ramp { display: flex; align-items: center; gap: 14px; }
.ramp-name { width: 64px; flex: none; font-size: 13px; color: var(--color-text-sub-600, #64625c); text-align: right; }
.ramp-steps { display: flex; flex: 1; height: 44px; border-radius: var(--radius-8, 8px); overflow: hidden; border: 1px solid var(--color-stroke-soft-200, #ebebeb); }
.ramp-step { flex: 1; display: flex; align-items: flex-end; justify-content: center; padding-bottom: 4px; }
.ramp-step em { font-style: normal; font-size: 10px; color: rgba(0,0,0,0.45); mix-blend-mode: difference; filter: invert(1) grayscale(1) contrast(9); }
table.scale { border-collapse: collapse; width: 100%; font-size: 14px; }
table.scale td { padding: 8px 12px; border-bottom: 1px solid var(--color-stroke-soft-200, #ebebeb); }
table.scale td:first-child { width: 40%; }
.cat-head { font-size: 12px; text-transform: uppercase; letter-spacing: 0.07em; color: var(--color-text-sub-600, #a3a3a3); font-weight: 500; margin: 28px 0 12px; }
.comp-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 14px; }
.comp-card { display: flex; flex-direction: column; text-decoration: none; border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-8, 8px); overflow: hidden; transition: border-color .15s ease; }
.comp-card:hover { border-color: var(--color-primary-base, #335cff); }
.comp-card-meta { padding: 12px 14px; display: flex; flex-direction: column; gap: 3px; }
.comp-card-meta strong { font-weight: 500; display: flex; align-items: center; gap: 8px; }
.comp-card-meta > span { color: var(--color-text-sub-600, #5c5c5c); font-size: 13px; line-height: 1.4; min-height: 2.8em; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.crumb { font-size: 13px; color: var(--color-text-sub-600, #a3a3a3); margin-bottom: 12px; }
.crumb a { color: inherit; }
.stage { display: flex; flex-wrap: wrap; gap: 16px; align-items: center; padding: 36px; border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-16, 16px); background: var(--color-bg-weak-50, #f7f7f7); }
.stage--thumb { padding: 22px; height: 132px; box-sizing: border-box; overflow: hidden; justify-content: center; border: 0; border-bottom: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: 0; }
.code { background: var(--color-bg-weak-50, #f7f7f7); border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-8, 8px); padding: 12px 14px; overflow-x: auto; font-size: 13px; margin: 0; }
.tag { display: inline-block; font-size: 12px; padding: 2px 9px; border-radius: var(--radius-full, 999px); background: var(--color-bg-weak-50, #f7f7f7); border: 1px solid var(--color-stroke-soft-200, #ebebeb); margin: 2px 0; }
.tags { line-height: 2.2; }
.tokenlist, .do, .dont { padding-left: 0; list-style: none; }
.anatomy { margin: 16px 0 0; padding-left: 0; counter-reset: part; list-style: none; }
.anatomy li { padding: 6px 0 6px 34px; border-bottom: 1px solid var(--color-stroke-soft-200, #ebebeb); position: relative; }
.anatomy li::before {
  counter-increment: part; content: counter(part);
  position: absolute; left: 0; top: 7px;
  width: 22px; height: 22px; display: inline-flex; align-items: center; justify-content: center;
  font-size: 12px; font-weight: var(--font-weight-medium, 500);
  color: var(--color-primary-base, #335cff);
  border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: 999px;
}
.muted { color: var(--color-text-soft-400, #a3a3a3); font-size: 12px; }
.section-note { font-size: 14px; color: var(--color-text-sub-600, #64625c); margin: -4px 0 16px; }

/* Specs (redline) table */
table.specs { border-collapse: collapse; width: 100%; font-size: 14px; }
table.specs th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: var(--color-text-soft-400, #a3a3a3); font-weight: 500; padding: 0 12px 8px; border-bottom: 1px solid var(--color-stroke-soft-200, #ebebeb); }
table.specs td { padding: 9px 12px; border-bottom: 1px solid var(--color-stroke-soft-200, #eeece5); vertical-align: middle; }
table.specs td:first-child { color: var(--color-text-sub-600, #64625c); width: 34%; }
table.specs td.mono { width: 30%; color: var(--color-text-strong-950, #141413); }
table.specs code { font-size: 13px; }

/* Per-variant Specs / Code tabs sit under the live stage */
.code-caption { font-size: 12px; color: var(--color-text-soft-400, #a3a3a3); margin: 14px 0 8px; }
.tabpanel .code-wrap + .code-caption { margin-top: 16px; }
.tabpanel table.specs { margin: 0; }
.tabpanel table.specs th { padding-top: 0; }
.tabpanel table.specs tr:last-child td { border-bottom: 0; }

/* Interaction states grid */
.state-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 12px; }
.state-cell { margin: 0; display: flex; flex-direction: column; gap: 8px; }
.stage--state { padding: 20px; min-height: 76px; justify-content: center; margin: 0; }
.state-cell figcaption { font-size: 12px; color: var(--color-text-secondary, #64625c); text-align: center; }
.tokenlist li { padding: 6px 0; }
.usage { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; }
.do li, .dont li { padding: 6px 0 6px 22px; position: relative; }
.do li::before { content: "+"; position: absolute; left: 0; color: var(--color-primary-base, #335cff); }
.dont li::before { content: "\\2013"; position: absolute; left: 0; color: var(--color-text-sub-600, #a3a3a3); }
.connected { font-size: 14px; color: var(--color-primary-base, #335cff); }
.unconnected { font-size: 14px; color: var(--color-text-sub-600, #a3a3a3); }

/* Live component demos (.ds-* classes) live in design-system/demos/demos.css,
   linked separately, so the demo styles are one file the whole team edits. */

/* --- Variant gallery on component pages --- */
.variant { margin: 0 0 20px; border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-16, 16px); overflow: hidden; }
.variant-head { padding: 16px 18px 0; }
.variant-head h3 { margin: 0; font-size: 16px; font-weight: 500; text-transform: none; letter-spacing: 0; color: var(--color-text-strong-950, #171717); border: 0; padding: 0; }
.variant-desc { margin: 4px 0 0; color: var(--color-text-sub-600, #5c5c5c); font-size: 14px; }
.stage--variant { margin: 16px 18px; border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-8, 8px); }
.stage-empty { color: var(--color-text-sub-600, #a3a3a3); font-size: 13px; font-style: italic; }

/* Tabs: Usage / CSS */
.tabs { border-top: 1px solid var(--color-stroke-soft-200, #ebebeb); }
.tablist { display: flex; gap: 2px; padding: 0 10px; border-bottom: 1px solid var(--color-stroke-soft-200, #ebebeb); }
.tab { font: inherit; font-size: 13px; cursor: pointer; padding: 10px 12px; background: transparent; border: 0; border-bottom: 2px solid transparent; margin-bottom: -1px; color: var(--color-text-sub-600, #5c5c5c); }
.tab:hover { color: var(--color-text-strong-950, #171717); }
.tab.is-active { color: var(--color-text-strong-950, #171717); border-bottom-color: var(--color-primary-base, #335cff); }
.tabpanel { padding: 16px 18px; }
.tabpanel.is-hidden { display: none; }
.code-wrap { display: flex; align-items: flex-start; gap: 12px; }
.code-wrap .code { flex: 1; min-width: 0; }
.code-actions { flex: none; }
.tabpanel .code { border: 0; border-radius: 0; background: transparent; margin: 0; padding: 0; }

/* Solo snippet (import block) */
.snippet--solo { border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-8, 8px); }
.snippet-bar { display: flex; align-items: center; justify-content: space-between; padding: 12px 14px 6px; }
.snippet-bar span { font-size: 11px; text-transform: uppercase; letter-spacing: 0.07em; color: var(--color-text-sub-600, #a3a3a3); font-weight: 500; }
.snippet--solo .code { border: 0; border-radius: 0; background: transparent; margin: 0; }

.copy { font: inherit; font-size: 12px; cursor: pointer; padding: 3px 11px; border: 1px solid var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-full, 999px); background: transparent; color: inherit; }
.copy:hover { border-color: var(--color-primary-base, #335cff); }
.copy.is-copied { color: var(--color-primary-base, #335cff); border-color: var(--color-primary-base, #335cff); }

/* Template / planned components */
.comp-card--template { border-style: dashed; }
.template-note { font-size: 14px; color: var(--color-text-sub-600, #5c5c5c); background: var(--color-bg-weak-50, #f7f7f7); border: 1px dashed var(--color-stroke-soft-200, #ebebeb); border-radius: var(--radius-8, 8px); padding: 12px 14px; }

@media (max-width: 720px) {
  .menu { display: flex; }
  .backdrop:not([hidden]) { display: block; }
  .layout { padding-left: 0; padding-top: 8px; }
  .side {
    top: 0; width: 82%; max-width: 320px;
    transform: translateX(-100%); transition: transform .22s ease;
  }
  body.nav-open .side { transform: translateX(0); box-shadow: var(--shadow-md, 0 4px 16px rgba(23,23,23,0.10)); }
  .usage { grid-template-columns: 1fr; }
}
`;
write(p('site/assets/site.css'), SITE_CSS.trim() + '\n');

write(p('site/index.html'), foundationsPage());
for (const c of allComponents) {
  write(p('site/components/' + slug(c.name) + '.html'), componentPage(c));
}

// ---------- DESIGN-SYSTEM.md: the agent-readable handoff spec ----------
// One self-contained markdown file with every token and every component
// contract. Feed it to a coding agent ("read design-system/DESIGN-SYSTEM.md,
// then build X") and the output uses tokens instead of raw values.
function tailwindKeyFor(name) {
  const [head, ...rest] = name.split('/');
  const tail = rest.join('-');
  if (head === 'color') return `colors.${tail}`;
  if (head === 'space') return `spacing.${tail}`;
  if (head === 'radius') return `borderRadius.${tail}`;
  if (head === 'font' && rest[0] === 'size') return `fontSize.${rest.slice(1).join('-')}`;
  if (head === 'font' && rest[0] === 'weight') return `fontWeight.${rest.slice(1).join('-')}`;
  if (head === 'shadow') return `boxShadow.${tail}`;
  return '';
}

function mdTokenTable(items, { dark = true } = {}) {
  const head = dark
    ? '| Token | CSS variable | Light | Dark |\n|---|---|---|---|'
    : '| Token | CSS variable | Value |\n|---|---|---|';
  const rows = items.map((t) => {
    const l = cssValue(t.name, t, 'light') ?? String(t.light ?? '');
    const d = cssValue(t.name, t, 'dark') ?? String(t.dark ?? '');
    return dark
      ? `| \`${t.name}\` | \`var(${cssVar(t.name)})\` | \`${l}\` | \`${d !== l ? d : l}\` |`
      : `| \`${t.name}\` | \`var(${cssVar(t.name)})\` | \`${l}\` |`;
  });
  return [head, ...rows].join('\n');
}

function mdComponent(c) {
  const lines = [];
  lines.push(`### ${c.name}`);
  const meta = [
    `status: ${statusOf(c)}`,
    `category: ${c.category || 'Components'}`,
    c.codeConnected ? `code: \`${c.codePath || ''}\`` : 'code: **not built yet — do not hand-roll; scaffold it from this spec and mark it code-connected**',
  ];
  lines.push('');
  lines.push(meta.map((m) => `- ${m}`).join('\n'));
  if (c.description) lines.push('', c.description);
  if (c.usage?.import) lines.push('', '```js', c.usage.import, '```');
  const states = c.states || [];
  if (c.props?.length) {
    lines.push('', '**Props**', '', '| Prop | Values |', '|---|---|');
    for (const pr of c.props || []) lines.push(`| \`${pr.name}\` | ${(pr.values || []).map((v) => `\`${v}\``).join(' ')} |`);
  }
  if (states.length) lines.push('', `**Interaction states:** ${states.join(', ')}`);
  if (c.anatomy?.length) lines.push('', `**Anatomy:** ${c.anatomy.map((a, i) => `${i + 1}. ${a}`).join(' ')}`);
  if (!getSpecs(c).base.length && c.tokensUsed?.length) {
    lines.push('', `**Tokens used:** ${c.tokensUsed.map((t) => `\`${t}\``).join(', ')}`);
  }
  // Per-variant: the TSX call a developer writes + that variant's redline specs
  // (shared base rows merged with rows specific to this variant).
  const { base: specBase, byVariant } = getSpecs(c);
  const mdSpecRow = (r) => r.token
    ? `| ${r.prop} | \`${r.token}\` | \`${(flat[r.token] ? (cssValue(r.token, flat[r.token], 'light') ?? String(flat[r.token].light ?? '')) : '')}\` |`
    : `| ${r.prop} | (literal) | \`${r.value ?? ''}\` |`;
  const dvariants = (demoFor(c)?.variants) || [];
  const exVariants = dvariants.length ? dvariants : (c.examples || []).map((ex) => ({ title: ex.title, description: ex.description, tsx: ex.usage }));
  for (const ex of exVariants) {
    if (!ex.tsx && !specBase.length) continue;
    lines.push('', `**${ex.title || 'Example'}**${ex.description ? ` — ${ex.description}` : ''}`);
    if (ex.tsx) lines.push('', '```jsx', ex.tsx, '```');
    const rows = [...specBase, ...(byVariant[ex.title] || [])];
    const tw = tailwindFromSpecs(rows);
    if (tw) lines.push('', '```jsx', `<div className="${tw}">…</div>`, '```');
    if (rows.length) {
      lines.push('', '| Property | Token | Value |', '|---|---|---|', ...rows.map(mdSpecRow));
    }
  }
  const dos = c.usage?.do || [], donts = c.usage?.dont || [];
  if (dos.length || donts.length) {
    lines.push('');
    for (const d of dos) lines.push(`- Do: ${d}`);
    for (const d of donts) lines.push(`- Don't: ${d}`);
  }
  return lines.join('\n');
}

function designSystemMd() {
  const name = raw.meta?.name || 'Design system';
  const bySeg = (seg) => Object.values(
    Object.entries(flat).filter(([n]) => n.startsWith(seg)).reduce((acc, [n, r]) => (acc[n] = { name: n, ...r }, acc), {})
  );
  const semanticColors = bySeg('color/').filter((t) => t.collection !== 'primitives');
  const primitiveColors = bySeg('color/').filter((t) => t.collection === 'primitives');
  const semGroups = new Map();
  for (const t of semanticColors) {
    const g = t.name.split('/')[1];
    if (!semGroups.has(g)) semGroups.set(g, []);
    semGroups.get(g).push(t);
  }
  const primGroups = new Map();
  for (const t of primitiveColors) {
    const g = t.name.split('/')[1];
    if (!primGroups.has(g)) primGroups.set(g, []);
    primGroups.get(g).push(t);
  }

  const out = [];
  out.push(`# ${name} — full specification`);
  out.push('');
  out.push(`> Generated by \`design-system/scripts/build.mjs\` from Figma variables${raw.meta?.template ? ` (structure: ${raw.meta.template})` : ''}. Do not edit by hand — change the Figma variables (or \`tokens/figma.raw.json\`) and rebuild. Last built ${new Date().toISOString().slice(0, 10)}.`);
  out.push('');
  out.push('## How to use this file (read this first, especially if you are an AI agent)');
  out.push('');
  out.push(`This file is the complete contract of the ${name}. When building any UI in this repository:`);
  out.push('');
  out.push('1. **Never hardcode a color, radius, spacing, shadow, or font value.** Every visual value must come from a token below, consumed as a CSS variable (`var(--color-bg-white-0)`) or a Tailwind theme key (`bg-bg-white-0`, from `design-system/tokens/tailwind.theme.js`).');
  out.push('2. **Use semantic color tokens** (`color/bg/*`, `color/text/*`, `color/icon/*`, `color/stroke/*`, `color/state/*`, `color/primary/*`) in product UI. Primitive scales (`color/blue/500`, …) exist to define semantics — do not use them directly in components.');
  out.push('3. **Check the component catalog below before writing a new component.** If the component exists and is code-connected, import it from the listed path. If it exists but is not built yet, scaffold it from its spec (props, states, tokens) rather than inventing your own API.');
  out.push('4. **Dark mode is automatic** when you use the tokens: `variables.css` swaps values under `[data-theme="dark"]` / `prefers-color-scheme`. Never write `dark:`-style one-off colors that bypass tokens.');
  out.push('5. **State colors map to intent**, not to hue: success=green, error=red, warning=orange, information=blue, away=yellow, feature=purple, verified=sky, highlighted=pink, stable=teal, faded=gray. Pick by meaning.');
  out.push('6. After generating UI code, run `node design-system/scripts/lint.mjs --code <dir>` to verify nothing drifted from the tokens.');
  out.push('');
  out.push('**Consumption artifacts** (regenerate with `node design-system/scripts/build.mjs`):');
  out.push('');
  out.push('| Artifact | Use |');
  out.push('|---|---|');
  out.push('| `design-system/tokens/variables.css` | Import once, globally. Defines every CSS variable, light + dark. |');
  out.push('| `design-system/tokens/tailwind.theme.js` | `theme: { extend: require("./design-system/tokens/tailwind.theme.js") }` |');
  out.push('| `design-system/tokens/tokens.json` | DTCG-style JSON, for any other toolchain. |');
  out.push('| `design-system/site/` | Human-readable docs site of the same content. |');
  out.push('');
  out.push('Naming convention: token `color/bg/white-0` → CSS `var(--color-bg-white-0)` → Tailwind `colors["bg-white-0"]` (class `bg-bg-white-0`, `text-text-strong-950`, `border-stroke-soft-200`, …).');

  out.push('', '## Color — semantic tokens (use these in UI)', '');
  const SEM_ORDER = ['bg', 'text', 'icon', 'stroke', 'primary', 'state', 'static'];
  const SEM_NOTES = {
    bg: 'Backgrounds, from page canvas (`white-0`) to inverted surfaces (`strong-950`).',
    text: 'Text colors by emphasis: strong → sub → soft → disabled.',
    icon: 'Icon colors, same emphasis ladder as text.',
    stroke: 'Borders and dividers.',
    primary: 'The brand/action color. Rebrand a project by repointing these (and the alpha primitives) — nothing else changes.',
    state: 'Intent colors. Per state: `lighter` (tinted bg), `light` (borders/accents on tint), `base` (the color), `dark` (text on tint).',
    static: 'Never flip in dark mode.',
  };
  const semKeys = [...SEM_ORDER.filter((k) => semGroups.has(k)), ...[...semGroups.keys()].filter((k) => !SEM_ORDER.includes(k))];
  for (const key of semKeys) {
    out.push(`### color/${key}`, '');
    if (SEM_NOTES[key]) out.push(SEM_NOTES[key], '');
    out.push(mdTokenTable(semGroups.get(key)), '');
  }

  out.push('## Color — primitive scales (define semantics only; do not use directly)', '');
  for (const [key, items] of primGroups) {
    if (semGroups.has(key)) continue;
    out.push(`### color/${key}`, '');
    out.push(mdTokenTable(items, { dark: false }), '');
  }

  const simpleSection = (title, seg, note, dark = false) => {
    const items = bySeg(seg);
    if (!items.length) return;
    out.push(`## ${title}`, '');
    if (note) out.push(note, '');
    out.push(mdTokenTable(items, { dark }), '');
  };
  simpleSection('Radius', 'radius/', 'Pixel radii. `radius/full` is a pill/circle.');
  simpleSection('Spacing', 'space/', 'A 4px grid. Use these for padding, gaps, and margins.');
  simpleSection('Typography', 'type/', 'Text styles as CSS `font` shorthand (`weight size/line-height family`). Titles for headings, Label for UI text and buttons (medium weight), Paragraph for body copy, Subheading for uppercase eyebrows/overlines.');
  simpleSection('Font primitives', 'font/');
  simpleSection('Shadows', 'shadow/', 'Elevation. `xs` for cards and inputs, `sm` for dropdowns/popovers, `md` for modals and drawers.');

  out.push('## Components', '');
  out.push('Status legend: **stable**/**beta** exist in Figma (and in code when a path is listed); **planned** components have an agreed spec but no Figma/code yet — build them from the spec, then promote them in `design-system/inventory/components.json`.', '');
  for (const [cat, items] of componentGroups()) {
    out.push(`## Components — ${cat}`, '');
    for (const c of items) out.push(mdComponent(c), '', '---', '');
  }

  out.push('## Changing the system', '');
  out.push('- Figma variables are the single source of truth. Change flows one way: Figma → `tokens/figma.raw.json` → build → code/docs.');
  out.push('- To change a value (color, radius, spacing): edit the Figma variable (or ask the design-system skill to "propagate" the change), re-pull, and rebuild. Never patch generated files.');
  out.push('- To add a component: add it to Figma and the inventory (or promote a planned template), then rebuild.');
  out.push('- Lint for drift: `node design-system/scripts/lint.mjs` (Figma screens) and `node design-system/scripts/lint.mjs --code src/` (your source code).');
  out.push('');
  return out.join('\n');
}

write(p('DESIGN-SYSTEM.md'), designSystemMd());

const plannedCount = plannedTemplates.length;
console.log(`Built: ${Object.keys(flat).length} tokens, ${allComponents.length} component pages${plannedCount ? ` (${plannedCount} planned from templates)` : ''} -> site/ + DESIGN-SYSTEM.md`);
